# Generated by Django 5.0.6 on 2024-07-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_university_asistencia_id_user_estudiante_id_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='Estudiante',
            new_name='estudiante',
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='id_Asistencia',
            new_name='id_asistencia',
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='id_user',
            new_name='user',
        ),
    ]
